### ISSUE TITLE
Questions about document maintenance

### ISSUE THREAD

**Issue by Ares-Chang** [Alfred-Skyblue/unocss-docs-cn#3]
您好，我想了解以下几个问题：

1. 这个文档是否准备长期维护，可同步 unocss 英文文档内容。
2. 是否有准备分享至 unocss 文档中
3. 是否可接受 #2  我的润色风格

如果可以接受的话，我也想为文档做一份贡献(ps: 可能不定期)

另外我没有做过这类了解，我想知道一下，你是怎么做文档初期大规模机翻的，是否可以分享一下，感谢。

**Comment by Alfred-Skyblue** [comment]
感谢您的提问，在这里对您进行答复：

1. 文档会长期更新维护，会定期同步unocss官方文档内容。
2. 我很乐意将文档分享至unocss官方文档灰总
3. 我很乐意接受大家的参与

如果您可以参与到文档的维护当中，对我来说是一件很荣幸的事，谢谢！

**Comment by Ares-Chang** [comment]
Thanks!
