### ISSUE TITLE
部分翻译落后

### ISSUE THREAD

**Issue by dufu1991** [Alfred-Skyblue/unocss-docs-cn#5]
最近查看中文文档发现这个部分与官方文档完全不一样，可能是没有及时更新。https://unocss.dev/guide/extracting。
搜索引擎能搜到的第一个标记中文的站点，原本以为是官网，即使不是也应该不会落后官网很多，实际还是有很多不一样，会存在一定的误导性。

**Comment by dufu1991** [comment]
而且奇怪的是查看官网底部 https://unocss.dev/guide/extracting 这个页面最后更新时间是 6/27/23, 4:28 PM，中文文档是 2023/7/10 10:32:27 ，更新时间在后，内容反而没跟上？

**Comment by Alfred-Skyblue** [comment]
已更新，谢谢提醒
